### ISSUE TITLE
Feedback on Install - Note Volumes

### ISSUE THREAD

**Issue by FreeSoftwareServers** [alubbock/samba-docker#2]
Hey Alubbock! Thanks for this great work, I prefer to use smb.conf not just because I already had it, but because the internet resources will regard editing smb.conf and I don't want to have to translate that into environment variables!

My main gripe was after I got it running I noticed a bunch of docker-volumes created which I don't like as I strickly use bind mounts. I thought I'd share my notes anyway, I got it running now along with NFS! I'm ready to re-deploy my server and my plan is to not install ANYTHING via apt and be 100% dockerized.

https://www.freesoftwareservers.com/display/FREES/Configure+SAMBA+-+SMB+-+Docker-Compose+-+Using+SMB.CONF

**Docker-Compose:**

```
WD=/opt/smbd
mkdir -p $WD/{mnt,setup,smb_conf,smb_data,smb_logs,smb_cache,smb_etc}
cd $WD/setup
curl https://raw.githubusercontent.com/alubbock/samba-docker/master/Dockerfile > Dockerfile
cat << 'EOF' >docker-compose.yaml
version: '3.7'

services:
 smbd:
    container_name: smbd
    hostname: smbd
    build: .
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - type: bind
        read_only: true
        source: /opt/smbd/smb_conf/
        target: /etc/samba
      - type: bind
        source: /opt/smbd/smb_data/
        target: /var/lib/samba
      - type: bind
        source: /opt/smbd/smb_logs/
        target: /var/log/samba
      - type: bind
        source: /opt/smbd/smb_etc/
        target: /etc
      - type: bind
        source: /var/run/samba/
        target: /run/samba
      - type: bind
        source: /opt/smbd/smb_cache/
        target: /var/cache/samba
      - type: bind
        source: /mnt
        target: /mnt
    environment:
      - 'TZ=America/Whitehorse'
EOF
chmod +x docker-compose.yaml
```

**SystemD:**

```
WD=/opt/smbd/setup
cat << EOF >$WD/smbd.service.setup.sh
cat << EOL >/lib/systemd/system/smbd.service
[Unit]
Description=smbd_Docker
Requires=docker.service network-online.target

[Service]

Restart=on-abnormal
ExecStart=/usr/bin/docker-compose --project-name smbd --project-directory $WD -f $WD/docker-compose.yaml up
ExecStop=/usr/bin/docker-compose --project-name smbd --project-directory $WD -f $WD/docker-compose.yaml stop

[Install]
WantedBy=multi-user.target
EOL
systemctl enable smbd
systemctl restart smbd
systemctl status smbd
EOF
chmod +x $WD/smbd.service.setup.sh
$WD/smbd.service.setup.sh
```
